[package]
name = "px2ansi-rs"
version = "0.1.2"
edition = "2024"
authors = [
	"T. Sawyer <saylesss87@proton.me>",
	"Nell Fauveau <nellousan@hotmail.fr> (original Python version)",
]
license = "GPL-3.0"
description = "Convert pixel art images to ANSI terminal art (Rust port)"
repository = "https://github.com/saylesss88/px2ansi-rs"
readme = "README.md"
keywords = ["ansi", "pixel-art", "terminal", "image", "cli"]
categories = ["command-line-utilities", "multimedia::images", "rendering"]

[dependencies]
image = "0.25"
clap = {version = "4.5", features = ["derive"]}
anyhow = "1.0"
terminal_size = "0.4.3"

[[bin]]
name = "px2ansi-rs"
path = "src/main.rs"

[lib]
name = "px2ansi_rs"
path = "src/lib.rs"
